export const FETCH_GNOMES_BEGIN = 'FETCH_GNOMES_BEGIN';
export const FETCH_GNOMES_SUCCESS = 'FETCH_GNOMES_SUCCESS';
export const FETCH_GNOMES_FAILURE = 'FETCH_GNOMES_FAILURE';
export const SET_API_ERROR = 'SET_API_ERROR';
export const RESET_API_ERROR = 'RESET_API_ERROR';
export const SET_API_SUCCESS = 'SET_API_SUCCESS';
export const RESET_API_SUCCESS = 'RESET_API_SUCCESS';
export const SET_NETWORK_ERROR = 'SET_NETWORK_ERROR';
